server:
  port: 8080

spring:
  datasource:
    # You can set SPRING_DATASOURCE_URL to point to an external DB (e.g. Supabase Postgres)
    # Example Supabase JDBC URL: jdbc:postgresql://db.hostname.supabase.co:5432/postgres
    # If SPRING_DATASOURCE_URL is set, it will be used. Otherwise, the MySQL local defaults are used.
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:deportur}}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
